from sqlmodel import SQLModel, Field


class Tickets(SQLModel, table=True):
    __tablename__ = 'swtickets'

    ticketid: int = Field(default=None, primary_key=True)
    ticketmaskid: int
    departmentid: int
    departmenttitle: str
    ticketstatusid: int
    ticketstatustitle: str
    priorityid: int
    prioritytitle: str
    emailqueueid: int
    userid: int
    staffid: int
    ownerstaffid: int
    ownerstaffname: str
    assignstatus: bool
    fullname: str
    email: str
    lastreplier: str
    replyto: str
    subject: str
    dateline: int
    lastactivity: int
    laststaffreplytime: int
    lastuserreplytime: int
    slaplanid: int
    ticketslaplanid: int
    duetime: int
    totalreplies: int
    ipaddress: str
    flagtype: bool
    hasnotes: bool
    hasattachments: bool
    isemailed: bool
    edited: bool
    editedbystaffid: int
    editeddateline: int
    creator: bool
    charset: str
    transferencoding: str
    timeworked: int
    timebilled: int
    dateicon: int
    lastpostid: int
    firstpostid: int
    tgroupid: int
    messageid: int
    escalationruleid: int
    hasdraft: bool
    hasbilling: bool
    isphonecall: bool
    isescalated: bool
    isescalatedvolatile: bool
    phoneno: str
    isautoclosed: bool
    autocloseruleid: int
    autoclosestatus: bool
    autoclosetimeline: int
    escalatedtime: int
    followupcount: int
    hasfollowup: bool
    hasratings: bool
    tickethash: str
    islinked: bool
    trasholddepartmentid: int
    tickettype: bool
    tickettypeid: int
    tickettypetitle: str
    creationmode: bool
    isfirstcontactresolved: bool
    wasreopened: bool
    reopendateline: int
    resolutiondateline: int
    escalationlevelcount: int
    resolutionseconds: int
    resolutionlevel: int
    repliestoresolution: int
    averageresponsetime: int
    averageslaresponsetime: int
    averageresponsetimehits: int
    firstresponsetime: int
    resolutionduedateline: int
    isresolved: bool
    iswatched: bool
    oldeditemailaddress: str
    recurrencefromticketid: int
    linkkbarticleid: int
    linkticketmacroid: int
    bayescategoryid: int
    ticketclosedateline: int
    